export const initialValues = {
    hiringCompany: "",
    projectName: "",
    identifier:"",
    addressDescription: "",
    address: "",
    block: "",
    unit: "",
    zipCode: "",
    province: "",
    map: "lat: 36.579395, lng: -4.597678",
    typeOfWork: "construccion",
    constructionType: "otra",
    projectDetails: "",
    startDate: "",
    endDate: "",
    sections: {
      livingRoom: false,
      kitchen: false,
      hall: false,
      room: false,
      bathRoom: false,
      terrace: false,
      laundry: false,
      pool: false,
      roof: false
    },
    addedSection: "",
    createTask: "",
    area: "",
    projectDescription: "",
    taskDescription: "",
    status: "noIniciado",
    image:""
  }
  